/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client_server;

import client_server.Files;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abdullah
 */
public class ServerFiles extends javax.swing.JFrame {
    
    ArrayList<Files> myfiles;
    int id = -1;
    static DataInputStream dataInputStream;
    static DataOutputStream dataOutputStream;
    static DefaultTableModel dModel;
    static int totalfile_row;
    int count = 0;

    /**
     * Creates new form ServerFiles
     */
    public ServerFiles() {
        initComponents();
    }
    
    public ServerFiles(ArrayList<Files> myfiles, DataOutputStream dataOutputStream, DataInputStream dataInputStream) {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        totalfile_row = myfiles.size();
        System.out.println(myfiles.size());
        count = 1;
        this.myfiles = myfiles;
        this.dataOutputStream = dataOutputStream;
        this.dataInputStream = dataInputStream;
        dModel = (DefaultTableModel) serverFileList.getModel();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        serverFileList.setDefaultRenderer(String.class, centerRenderer);
        for (int columnIndex = 0; columnIndex < serverFileList.getColumnCount(); columnIndex++) {
            serverFileList.getColumnModel().getColumn(columnIndex).setCellRenderer(centerRenderer);
        }
        if (count > 1) {
               dModel.insertRow(5, new Object[]{myfiles.get(5).getId(), myfiles.get(5).getName()});
        }
        for (Files myfile : myfiles) {
            count++;
            dModel.addRow(new Object[]{myfile.getId(), myfile.getName()});
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        serverFileList = new javax.swing.JTable();
        downloadFile = new javax.swing.JButton();
        deleteFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        serverFileList.setAutoCreateRowSorter(true);
        serverFileList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "                                Id", "                      File Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        serverFileList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serverFileListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(serverFileList);
        if (serverFileList.getColumnModel().getColumnCount() > 0) {
            serverFileList.getColumnModel().getColumn(0).setResizable(false);
            serverFileList.getColumnModel().getColumn(1).setResizable(false);
        }

        downloadFile.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        downloadFile.setText("Download");
        downloadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadFileActionPerformed(evt);
            }
        });

        deleteFile.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        deleteFile.setText("Delete");
        deleteFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(downloadFile, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(deleteFile, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(downloadFile)
                    .addComponent(deleteFile))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void downloadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadFileActionPerformed
        if (serverFileList.getRowCount() != 0) {
            if (id != -1) {
                for (Files myFile : myfiles) {
                    if (myFile.getName() == dModel.getValueAt(id, 1)) {
                        JFrame jfPreview = createFrame(myFile.getName(), myFile.getData(), myFile.getFileExtension());
                        jfPreview.setVisible(true);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please Select a file first", "Alert", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Table is empty !", "Alert", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_downloadFileActionPerformed

    private void deleteFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFileActionPerformed
        if (serverFileList.getRowCount() != 0) {
            if (id != -1) {
                for (Files myFile : myfiles) {
                    if (myFile.getName() == dModel.getValueAt(serverFileList.getSelectedRow(), 1)) {
                        JFrame jfRemove = createFrameToRemove(myFile.getName(), myFile.getData(), myFile.getFileExtension());
                        jfRemove.setVisible(true);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please Select a file first", "Alert", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Table is empty !", "Alert", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteFileActionPerformed

    private void serverFileListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serverFileListMouseClicked
        id = serverFileList.getSelectedRow();
        System.out.println(serverFileList.getSelectedRow() + " " + serverFileList.getSelectedColumn());
    }//GEN-LAST:event_serverFileListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerFiles().setVisible(true);
            }
        });
    }
    
    public static JFrame createFrame(final String fileName, final byte[] fileData, String fileExtension) {

        final JFrame jFrame = new JFrame("File Downloader");
        jFrame.setSize(500, 400);
        JPanel jPanel = new JPanel();
        jPanel.setLayout(new BoxLayout(jPanel, BoxLayout.Y_AXIS));
        JLabel jlTitle = new JLabel("Download File : " + fileName);
        jlTitle.setAlignmentX(Component.CENTER_ALIGNMENT);
        jlTitle.setFont(new Font("Courgette", Font.BOLD, 25));
        jlTitle.setBorder(new EmptyBorder(20, 0, 10, 0));
        JLabel jlPrompt = new JLabel("Are you sure you want to download " + fileName + "?");
        jlPrompt.setFont(new Font("Courgette", Font.BOLD, 20));
        jlPrompt.setBorder(new EmptyBorder(20, 0, 10, 0));
        jlPrompt.setAlignmentX(Component.CENTER_ALIGNMENT);
        JButton jbYes = new JButton("Yes");
        jbYes.setPreferredSize(new Dimension(100, 50));
        jbYes.setFont(new Font("Courgette", Font.BOLD, 20));
        JButton jbNo = new JButton("No");
        jbNo.setPreferredSize(new Dimension(100, 50));
        jbNo.setFont(new Font("Courgette", Font.BOLD, 20));
        JLabel jlFileContent = new JLabel();
        jlFileContent.setAlignmentX(Component.CENTER_ALIGNMENT);
        JPanel jpButtons = new JPanel();
        jpButtons.setBorder(new EmptyBorder(20, 0, 10, 0));
        jpButtons.add(jbYes);
        jpButtons.add(jbNo);
        if (fileExtension.equalsIgnoreCase("png") || fileExtension.equalsIgnoreCase("jpg") || fileExtension.equalsIgnoreCase("jpeg")
                || fileExtension.equalsIgnoreCase("gif") || fileExtension.equalsIgnoreCase("tiff")) {
            jlFileContent.setIcon(new ImageIcon(fileData));
        }

        jbYes.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFileChooser chooser = new JFileChooser();
                chooser.setCurrentDirectory(new java.io.File("."));
                chooser.setDialogTitle("choosertitle");
                chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                chooser.setAcceptAllFileFilterUsed(false);
                File fileToDownload = null;
                if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
                    System.out.println(chooser.getSelectedFile());
                    fileToDownload = new File(chooser.getSelectedFile() + "/" + fileName);
                    try {
                        FileOutputStream fileOutputStream = new FileOutputStream(fileToDownload);
                        fileOutputStream.write(fileData);
                        fileOutputStream.close();
                        jFrame.dispose();
                    } catch (IOException ex) {
                        ex.printStackTrace();
                    }
                } else {
                    System.out.println("No Selection ");
                }

            }
        });
        jbNo.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jFrame.dispose();
            }
        });
        jPanel.add(jlTitle);
        jPanel.add(jlPrompt);
        jPanel.add(jlFileContent);
        jPanel.add(jpButtons);
        jFrame.add(jPanel);
        return jFrame;

    }
    
    public static JFrame createFrameToRemove(final String fileName, final byte[] fileData, String fileExtension) {

        final JFrame jFrame = new JFrame("File Remover");
        jFrame.setSize(500, 400);
        JPanel jPanel = new JPanel();
        jPanel.setLayout(new BoxLayout(jPanel, BoxLayout.Y_AXIS));
        JLabel jlTitle = new JLabel("Remove File : " + fileName);
        jlTitle.setAlignmentX(Component.CENTER_ALIGNMENT);
        jlTitle.setFont(new Font("Courgette", Font.BOLD, 25));
        jlTitle.setBorder(new EmptyBorder(20, 0, 10, 0));
        JLabel jlPrompt = new JLabel("Are you sure you want to remove " + fileName + "?");
        jlPrompt.setFont(new Font("Courgette", Font.BOLD, 20));
        jlPrompt.setBorder(new EmptyBorder(20, 0, 10, 0));
        jlPrompt.setAlignmentX(Component.CENTER_ALIGNMENT);
        JButton jbYes = new JButton("Yes");
        jbYes.setPreferredSize(new Dimension(100, 50));
        jbYes.setFont(new Font("Courgette", Font.BOLD, 20));
        JButton jbNo = new JButton("No");
        jbNo.setPreferredSize(new Dimension(100, 50));
        jbNo.setFont(new Font("Courgette", Font.BOLD, 20));
        JLabel jlFileContent = new JLabel();
        jlFileContent.setAlignmentX(Component.CENTER_ALIGNMENT);
        JPanel jpButtons = new JPanel();
        jpButtons.setBorder(new EmptyBorder(20, 0, 10, 0));
        jpButtons.add(jbYes);
        jpButtons.add(jbNo);
        if (fileExtension.equalsIgnoreCase("png") || fileExtension.equalsIgnoreCase("jpg") || fileExtension.equalsIgnoreCase("jpeg")
                || fileExtension.equalsIgnoreCase("gif") || fileExtension.equalsIgnoreCase("tiff")) {
            jlFileContent.setIcon(new ImageIcon(fileData));
        }

        jbYes.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    dataOutputStream.writeUTF("remove");
                    dataOutputStream.writeUTF(fileName);
                    String back_message = dataInputStream.readUTF();
                    if (back_message.equals("file-deleted")) {
                        dModel.removeRow(serverFileList.getSelectedRow());
                    }
                    jFrame.dispose();
                } catch (IOException ex) {
                    Logger.getLogger(ServerFiles.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        jbNo.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jFrame.dispose();
            }
        });
        jPanel.add(jlTitle);
        jPanel.add(jlPrompt);
        jPanel.add(jlFileContent);
        jPanel.add(jpButtons);
        jFrame.add(jPanel);
        return jFrame;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteFile;
    private javax.swing.JButton downloadFile;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable serverFileList;
    // End of variables declaration//GEN-END:variables
}
